"""Main playlist sync workflow."""

import logging
import os
import time
import traceback

from ..config import Settings
from ..observability import (
    clear_failure_log,
    fire_webhook,
    get_history_db,
    record_sync_error,
    record_tracks_to_history,
    save_failure_log,
    save_run_log,
)
from ..playlist import get_playlist_statistics, log_playlist_statistics, sync_playlist
from ..playlist import reset_query_counter as reset_playlist_counter
from ..playlist.sync import InvalidVideoIDsError, _evict_from_cache, _retry_with_backoff
from ..playlist.weekly import update_weekly_playlist
from ..recency import WeightedTrack, collapse_recency_weighted, dedupe_keep_latest
from ..search import (
    get_search_statistics,
    log_search_statistics,
    reset_search_statistics,
    resolve_tracks_to_video_ids,
)
from ..ytm import create_playlist_with_items, get_existing_playlist_by_name
from ._common import build_context, fetch_scrobbles
from .backfill import reorder_after_backfill, run_backfill

log = logging.getLogger(__name__)


def run(settings: Settings) -> None:
    """Run the main playlist sync workflow."""
    _start = time.monotonic()
    ctx = build_context(settings)

    reset_search_statistics()
    reset_playlist_counter()

    recents = fetch_scrobbles(settings)
    if not recents:
        log.warning("No recent scrobbles found. Exiting.")
        return

    if settings.use_recency_weighting:
        tracks: list[WeightedTrack] = collapse_recency_weighted(
            recents,
            half_life_hours=settings.recency_half_life_hours,
            play_weight=settings.recency_play_weight,
            min_plays=settings.recency_min_plays,
        )
        log.info(
            "Aggregated to %d unique tracks (half-life=%.1fh). Resolving on YTM...",
            len(tracks),
            settings.recency_half_life_hours,
        )
    else:
        ordered = sorted(recents, key=lambda x: x.ts, reverse=True)
        tracks = dedupe_keep_latest(ordered) if settings.deduplicate else ordered  # type: ignore[assignment]
        log.info(
            "Prepared %d tracks (%s).",
            len(tracks),
            "deduped" if settings.deduplicate else "with repeats",
        )

    log.info("Resolving %d unique tracks on YTM...", len(tracks))

    video_ids, misses, track_to_vid, run_log_mappings = resolve_tracks_to_video_ids(
        ctx.ytm_search,
        tracks,
        settings.sleep_between_searches,
        settings.early_termination_score,
        ctx.search_cache,
        ctx.search_overrides,
        settings.api_max_retries,
        settings.search_max_workers,
    )

    bf = run_backfill(
        ctx,
        settings,
        recents=recents,
        tracks=list(tracks),
        video_ids=video_ids,
        track_to_vid=track_to_vid,
        run_log_mappings=run_log_mappings,
        misses=misses,
    )
    recents = bf.recents
    tracks = bf.tracks
    video_ids = bf.video_ids
    track_to_vid = bf.track_to_vid
    run_log_mappings = bf.run_log_mappings
    misses = bf.misses

    if bf.happened:
        tracks, video_ids, run_log_mappings = reorder_after_backfill(
            settings,
            recents=recents,
            tracks=tracks,
            video_ids=video_ids,
            track_to_vid=track_to_vid,
            run_log_mappings=run_log_mappings,
        )

    target_count = settings.limit
    if len(video_ids) < target_count:
        log.warning("Only found %d/%d unique tracks", len(video_ids), target_count)
    else:
        log.info("Found %d unique tracks", len(video_ids))

    if len(video_ids) > target_count:
        video_ids = video_ids[:target_count]

    original_count = len(video_ids)
    video_ids = list(dict.fromkeys(video_ids))
    if len(video_ids) < original_count:
        log.error(
            "BUG: Removed %d duplicate video IDs - deduplication should happen earlier",
            original_count - len(video_ids),
        )

    valid_video_ids = video_ids
    if not valid_video_ids:
        log.warning("No valid video IDs resolved")
        return

    ordering = "recency-weighted" if settings.use_recency_weighting else "most recent first"
    desc = settings.playlist_description or f"Autogenerated from Last.fm for {settings.lastfm_user} ({ordering})"

    existing_id = get_existing_playlist_by_name(ctx.ytm, settings.playlist_name, cache=ctx.playlist_cache)
    template_changed = ctx.playlist_cache.template_changed(settings.playlist_name, valid_video_ids)
    substitutions: dict[str, str] = {}

    if existing_id:
        log.info("Updating playlist '%s'...", settings.playlist_name)
        try:
            _retry_with_backoff(
                ctx.ytm.edit_playlist,
                existing_id,
                title=settings.playlist_name,
                description=desc,
                privacyStatus=settings.privacy_status,
                max_retries=settings.api_max_retries,
                operation="edit_playlist",
            )
        except Exception as e:
            log.warning("Failed to edit playlist metadata: %s", e)
        if template_changed:
            log.info("Syncing playlist...")
            try:
                substitutions = sync_playlist(ctx.ytm, existing_id, valid_video_ids, max_retries=settings.api_max_retries)
                ctx.playlist_cache.set_template(settings.playlist_name, existing_id, valid_video_ids)
            except InvalidVideoIDsError as e:
                _evict_from_cache(ctx.search_cache, e.invalid_ids)
                log.info("Re-resolving tracks after evicting %d invalid video IDs...", len(e.invalid_ids))
                video_ids, misses, track_to_vid, run_log_mappings = resolve_tracks_to_video_ids(
                    ctx.ytm_search,
                    tracks,
                    settings.sleep_between_searches,
                    settings.early_termination_score,
                    ctx.search_cache,
                    ctx.search_overrides,
                    settings.api_max_retries,
                    settings.search_max_workers,
                )
                valid_video_ids = list(dict.fromkeys(video_ids))
                if len(valid_video_ids) > target_count:
                    valid_video_ids = valid_video_ids[:target_count]
                log.info("Retrying sync with %d tracks...", len(valid_video_ids))
                substitutions = sync_playlist(ctx.ytm, existing_id, valid_video_ids, max_retries=settings.api_max_retries)
                ctx.playlist_cache.set_template(settings.playlist_name, existing_id, valid_video_ids)
            except Exception as e:
                error_msg = str(e)
                if "401" in error_msg or "Unauthorized" in error_msg:
                    log.exception("Sync failed: HTTP 401 - authentication expired")
                    save_failure_log("HTTP 401 - Unauthorized", traceback.format_exc())
                elif "403" in error_msg or "Forbidden" in error_msg:
                    log.exception("Sync failed: HTTP 403 - rate limit or auth expired")
                    save_failure_log("HTTP 403 - rate limit or auth expired", traceback.format_exc())
                elif "Expecting value" in error_msg:
                    log.exception("Sync failed: Invalid API response (likely rate limited)")
                    save_failure_log("Invalid API response (likely rate limited)", traceback.format_exc())
                else:
                    log.exception("Sync failed: %s", e)
                    save_failure_log(str(e), traceback.format_exc())
                record_sync_error(settings, e)
                fire_webhook(
                    settings,
                    status="error",
                    sync_type="main",
                    error=str(e),
                    tracks_resolved=len(valid_video_ids),
                    tracks_missed=misses,
                    duration_secs=time.monotonic() - _start,
                )
                raise
        else:
            log.info("Playlist already up to date")
            ctx.playlist_cache.touch(settings.playlist_name)

        pl_id = existing_id
    else:
        log.info("Creating playlist '%s'...", settings.playlist_name)
        try:
            pl_id = create_playlist_with_items(
                ctx.ytm,
                settings.playlist_name,
                desc,
                settings.privacy_status,
                valid_video_ids,
                cache=ctx.playlist_cache,
            )
            log.info("Created playlist with %d tracks", len(valid_video_ids))
        except Exception as e:
            log.exception("Create failed: %s", e)
            save_failure_log(f"Create failed: {e}", traceback.format_exc())
            record_sync_error(settings, e)
            fire_webhook(settings, status="error", sync_type="main", error=str(e), duration_secs=time.monotonic() - _start)
            raise

    weekly_id = update_weekly_playlist(
        ctx.ytm,
        get_existing_playlist_by_name,
        create_playlist_with_items,
        sync_playlist,
        settings=settings,
        valid_video_ids=valid_video_ids,
        base_desc=desc,
        cache=ctx.playlist_cache,
    )

    log.info("Done: https://music.youtube.com/playlist?list=%s", pl_id)
    if weekly_id:
        log.info("Weekly: https://music.youtube.com/playlist?list=%s", weekly_id)
    if misses:
        log.info("%d tracks not found", misses)

    clear_failure_log()
    save_run_log(run_log_mappings)

    log_search_statistics()
    log_playlist_statistics()

    ctx.search_cache.log_metrics("Search")
    ctx.playlist_cache.log_metrics("Playlist")

    override_stats = ctx.search_overrides.stats()
    if override_stats["total_overrides"] > 0 or override_stats["total_blacklisted"] > 0:
        log.info("Overrides: %d, Blacklisted: %d", override_stats["total_overrides"], override_stats["total_blacklisted"])

    cache_stats = ctx.search_cache._metrics.get_stats()
    search_stats = get_search_statistics()

    db = get_history_db(settings)
    if db:
        record_tracks_to_history(db, run_log_mappings, ctx.search_cache)
        source = os.environ.get("SYNC_TRIGGER", "cli")

        for original_id, replaced_id in substitutions.items():
            db.record_action(
                "substitution",
                video_id=replaced_id,
                detail=f"YTM substituted {original_id} → {replaced_id}",
                source=source,
            )

        db.record_action(
            "sync_complete",
            detail=f"resolved={len(valid_video_ids)}, missed={misses}, cache_hits={cache_stats['hits']}",
            source=source,
        )

        sync_id_str = os.environ.get("HISTORY_SYNC_ID")
        if sync_id_str:
            playlist_stats = get_playlist_statistics()
            override_stats_h = ctx.search_overrides.stats()
            db.finish_sync(
                int(sync_id_str),
                status="success",
                tracks_total=len(tracks),
                tracks_resolved=len(valid_video_ids),
                tracks_missed=misses,
                api_searches=search_stats.get("total_queries", 0),
                api_playlist_ops=playlist_stats.get("total_queries", 0),
                cache_hits=cache_stats["hits"],
                cache_misses=cache_stats["misses"],
                override_hits=override_stats_h.get("total_overrides", 0),
            )

        if settings.history_retention_days > 0:
            db.prune_by_age(settings.history_retention_days)
        if settings.history_max_size_mb > 0:
            db.prune_if_oversized(settings.history_max_size_mb)

    fire_webhook(
        settings,
        status="success",
        sync_type="main",
        tracks_resolved=len(valid_video_ids),
        tracks_missed=misses,
        tracks_total=len(tracks),
        duration_secs=time.monotonic() - _start,
        cache_hits=cache_stats["hits"],
        cache_misses=cache_stats["misses"],
        api_searches=search_stats.get("total_queries", 0),
        playlist_url=f"https://music.youtube.com/playlist?list={pl_id}",
    )
