version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: scope
    groups:
      python-dev:
        dependency-type: development
      python-prod:
        dependency-type: production

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: scope
    groups:
      npm-dev:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/devops"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: scope
