#!/usr/bin/env bash
#
# run-docker.sh - Start the lastfm-to-ytm web dashboard in Docker
#
# Usage: ./run-docker.sh [OPTIONS]
#   --rebuild, -r    Force rebuild the Docker image
#   --no-cache       Rebuild without using Docker cache (forces fresh install)
#   --stop           Stop the running container
#   --logs, -l       Follow container logs
#   --status         Show container status
#   --help, -h       Show this help message
#

set -euo pipefail

if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    CYAN='\033[0;36m'
    NC='\033[0m' # No Color
else
    RED='' GREEN='' YELLOW='' BLUE='' CYAN='' NC=''
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVOPS_DIR="$SCRIPT_DIR/devops"
CONTAINER_NAME="lastfm-to-ytm"
PORT="${YTMT_PORT:-2002}"
HEALTH_TIMEOUT="${YTMT_HEALTH_TIMEOUT:-30}"

if [[ -f "$DEVOPS_DIR/Dockerfile" ]]; then
    MODE="source"
    COMPOSE_FILE="$DEVOPS_DIR/docker-compose.yml"
    IMAGE_NAME="lastfm-to-ytm-web"
else
    MODE="standalone"
    COMPOSE_FILE="$SCRIPT_DIR/compose.standalone.yml"
    IMAGE_NAME="ghcr.io/locko2901/lastfm-to-ytm"
fi

compose_is_custom() {
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        return 1
    fi
    local expected
    expected=$(generate_compose_content)
    ! diff -q <(echo "$expected") "$COMPOSE_FILE" &>/dev/null
}

generate_compose_content() {
    cat <<'COMPOSE_EOF'
# Auto-generated by run-docker.sh - do not remove this line
services:
  lastfm-to-ytm:
    image: ghcr.io/locko2901/lastfm-to-ytm:latest
    container_name: lastfm-to-ytm
    restart: unless-stopped
    ports:
      - "${YTMT_PORT:-2002}:2002"
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
      - ./browser.json:/app/browser.json
      - ./.env:/app/.env
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=${TZ:-UTC}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
COMPOSE_EOF
}

generate_compose_file() {
    generate_compose_content > "$COMPOSE_FILE"
}

ensure_compose_file() {
    if [[ ! -f "$COMPOSE_FILE" ]]; then
        generate_compose_file
        return 0
    fi

    if compose_is_custom; then
        return 1
    fi

    generate_compose_file
    return 0
}

REBUILD=false
NO_CACHE=false
PRUNE=false
PRUNE_ALL=false
ACTION="start"  # default
for arg in "$@"; do
    case $arg in
        --rebuild|-r)
            REBUILD=true
            ;;
        --no-cache)
            REBUILD=true
            NO_CACHE=true
            ;;
        --stop)
            ACTION="stop"
            ;;
        --logs|-l)
            ACTION="logs"
            ;;
        --status)
            ACTION="status"
            ;;
        --prune)
            PRUNE=true
            ;;
        --prune-all)
            PRUNE=true
            PRUNE_ALL=true
            ;;
        --compose-only)
            ACTION="compose-only"
            ;;
        --help|-h)
            echo "Usage: ./run-docker.sh [OPTIONS]"
            echo
            echo "Options:"
            echo "  --rebuild, -r    Force rebuild (source) or pull latest (standalone)"
            echo "  --no-cache       Rebuild without using Docker cache (source mode only, implies --rebuild)"
            echo "  --stop           Stop the running container"
            echo "  --logs, -l       Follow container logs"
            echo "  --status         Show container status"
            echo "  --prune          Remove dangling images and old project images"
            echo "  --prune-all      Aggressive cleanup: also clear build cache and unused images"
            echo "                   Can be combined with --rebuild/--no-cache"
            echo "  --compose-only   Regenerate compose.standalone.yml (backs up custom edits)"
            echo "  --help, -h       Show this help message"
            echo
            echo "Environment variables:"
            echo "  YTMT_PORT            Port to expose (default: 2002)"
            echo "  YTMT_HEALTH_TIMEOUT  Seconds to wait for health check (default: 30)"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $arg${NC}"
            echo "Use --help for usage information."
            exit 1
            ;;
    esac
done

do_prune() {
    if [[ "$PRUNE_ALL" == true ]]; then
        echo -e "${CYAN}Pruning Docker resources (aggressive mode)...${NC}"
    else
        echo -e "${CYAN}Pruning Docker resources...${NC}"
    fi

    DANGLING=$(docker images -f "dangling=true" -q 2>/dev/null)
    if [[ -n "$DANGLING" ]]; then
        echo -e "${YELLOW}→ Removing dangling images...${NC}"
        docker rmi $DANGLING 2>/dev/null || true
        echo -e "${GREEN}✓ Dangling images removed${NC}"
    else
        echo -e "${GREEN}✓ No dangling images${NC}"
    fi

    OLD_IMAGES=$(docker images "$IMAGE_NAME" --format '{{.ID}}' | tail -n +2)
    if [[ -n "$OLD_IMAGES" ]]; then
        echo -e "${YELLOW}→ Removing old $IMAGE_NAME images...${NC}"
        echo "$OLD_IMAGES" | xargs -r docker rmi 2>/dev/null || true
        echo -e "${GREEN}✓ Old images removed${NC}"
    else
        echo -e "${GREEN}✓ No old project images${NC}"
    fi

    if [[ "$PRUNE_ALL" == true ]]; then
        BUILD_CACHE=$(docker builder du --format '{{.Size}}' 2>/dev/null | head -1)
        if [[ -n "$BUILD_CACHE" ]] && [[ "$BUILD_CACHE" != "0B" ]]; then
            echo -e "${YELLOW}→ Clearing build cache...${NC}"
            docker builder prune -f 2>/dev/null || true
            echo -e "${GREEN}✓ Build cache cleared${NC}"
        else
            echo -e "${GREEN}✓ No build cache to clear${NC}"
        fi

        echo -e "${YELLOW}→ Removing unused images...${NC}"
        docker image prune -a -f 2>/dev/null || true
        echo -e "${GREEN}✓ Unused images removed${NC}"
    fi

    echo
    echo -e "${CYAN}Current disk usage:${NC}"
    docker system df
}

if [[ "$PRUNE" == true ]] && [[ "$REBUILD" != true ]]; then
    do_prune
    exit 0
fi

case $ACTION in
    compose-only)
        if [[ "$MODE" != "standalone" ]]; then
            echo -e "${YELLOW}--compose-only is only for standalone mode (devops/docker-compose.yml already exists)${NC}"
            exit 1
        fi
        if compose_is_custom; then
            BACKUP="${COMPOSE_FILE}.bak"
            cp "$COMPOSE_FILE" "$BACKUP"
            echo -e "${YELLOW}→ Backed up customized compose.standalone.yml to compose.standalone.yml.bak${NC}"
        fi
        generate_compose_file
        echo -e "${GREEN}✓ Generated compose.standalone.yml${NC}"
        echo -e "  You can now use ${CYAN}docker compose -f compose.standalone.yml up -d${NC} directly."
        exit 0
        ;;
    stop)
        if [[ "$MODE" == "standalone" ]]; then
            ensure_compose_file
        fi
        echo -e "${CYAN}Stopping container...${NC}"
        docker compose -f "$COMPOSE_FILE" down
        echo -e "${GREEN}✓ Container stopped${NC}"
        exit 0
        ;;
    logs)
        if [[ "$MODE" == "standalone" ]]; then
            ensure_compose_file
        fi
        exec docker compose -f "$COMPOSE_FILE" logs -f
        ;;
    status)
        if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            echo -e "${GREEN}● Container is running${NC}"
            docker compose -f "$COMPOSE_FILE" ps
        else
            echo -e "${YELLOW}○ Container is not running${NC}"
        fi
        exit 0
        ;;
esac

echo -e "${CYAN}╔═══════════════════════════════════╗${NC}"
echo -e "${CYAN}║   lastfm-to-ytm Docker Launcher   ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════╝${NC}"
echo

echo -e "${BLUE}[1/5]${NC} Checking Docker installation..."
if ! command -v docker &> /dev/null; then
    echo -e "${RED}✗ Docker is not installed!${NC}"
    echo
    echo "Install Docker using one of these methods:"
    echo "  Ubuntu/Debian: sudo apt install docker.io docker-compose-v2"
    echo "  Snap:          sudo snap install docker"
    echo "  Official:      https://docs.docker.com/get-docker/"
    exit 1
fi
echo -e "${GREEN}✓ Docker is installed${NC}"

echo -e "${BLUE}[2/5]${NC} Checking Docker daemon..."
if ! docker info &> /dev/null; then
    echo -e "${RED}✗ Docker daemon is not running!${NC}"
    echo
    echo "Start Docker with:"
    echo "  sudo systemctl start docker"
    echo
    echo "Or if you need sudo for docker commands, run this script with sudo."
    exit 1
fi
echo -e "${GREEN}✓ Docker daemon is running${NC}"

echo -e "${BLUE}[3/5]${NC} Checking required files..."

if [[ "$MODE" == "standalone" ]]; then
    if ensure_compose_file; then
        echo -e "${YELLOW}→ Generated compose.standalone.yml${NC}"
    fi
fi

if [[ -d "$SCRIPT_DIR/.env" ]]; then
    echo -e "${YELLOW}→ Removing .env directory (Docker artifact)...${NC}"
    rm -rf "$SCRIPT_DIR/.env"
fi
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
    echo -e "${YELLOW}→ Creating empty .env file for first-time setup...${NC}"
    touch "$SCRIPT_DIR/.env"
fi

if [[ -d "$SCRIPT_DIR/browser.json" ]]; then
    echo -e "${YELLOW}→ Removing browser.json directory (Docker artifact)...${NC}"
    rm -rf "$SCRIPT_DIR/browser.json"
fi
if [[ ! -f "$SCRIPT_DIR/browser.json" ]]; then
    echo -e "${YELLOW}→ Creating empty browser.json for first-time setup...${NC}"
    echo '{}' > "$SCRIPT_DIR/browser.json"
fi

mkdir -p "$SCRIPT_DIR/cache" "$SCRIPT_DIR/config"

echo -e "${GREEN}✓ Required files exist${NC}"

echo -e "${BLUE}[4/5]${NC} Checking Docker image..."

if [[ "$MODE" == "standalone" ]]; then
    if [[ "$REBUILD" == true ]]; then
        echo -e "${YELLOW}→ Pulling latest image...${NC}"
        docker compose -f "$COMPOSE_FILE" pull || {
            echo -e "${RED}✗ Image pull failed${NC}"
            exit 1
        }
        echo -e "${GREEN}✓ Image pulled successfully${NC}"
    else
        IMAGE_EXISTS=$(docker images -q "$IMAGE_NAME" 2>/dev/null)
        if [[ -z "$IMAGE_EXISTS" ]]; then
            echo -e "${YELLOW}→ Pulling image for the first time...${NC}"
            docker compose -f "$COMPOSE_FILE" pull || {
                echo -e "${RED}✗ Image pull failed${NC}"
                exit 1
            }
            echo -e "${GREEN}✓ Image pulled successfully${NC}"
        else
            echo -e "${GREEN}✓ Image already exists${NC}"
            echo -e "  ${CYAN}(use --rebuild to pull the latest version)${NC}"
        fi
    fi
else
    IMAGE_EXISTS=$(docker images -q "$IMAGE_NAME" 2>/dev/null)

    if [[ -z "$IMAGE_EXISTS" ]] || [[ "$REBUILD" == true ]]; then
        if [[ "$REBUILD" == true ]]; then
            if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
                echo -e "${YELLOW}→ Stopping and removing old container...${NC}"
                docker compose -f "$COMPOSE_FILE" down --remove-orphans 2>/dev/null || true
            fi
        fi

        if [[ "$NO_CACHE" == true ]]; then
            echo -e "${YELLOW}→ Rebuilding image (--no-cache, full rebuild)...${NC}"
            docker compose -f "$COMPOSE_FILE" build --no-cache --pull || {
                echo -e "${RED}✗ Image build failed${NC}"
                exit 1
            }
        elif [[ "$REBUILD" == true ]]; then
            echo -e "${YELLOW}→ Rebuilding image (--rebuild flag)...${NC}"
            docker compose -f "$COMPOSE_FILE" build --pull || {
                echo -e "${RED}✗ Image build failed${NC}"
                exit 1
            }
        else
            echo -e "${YELLOW}→ Building image for the first time...${NC}"
            docker compose -f "$COMPOSE_FILE" build || {
                echo -e "${RED}✗ Image build failed${NC}"
                exit 1
            }
        fi
        echo -e "${GREEN}✓ Image built successfully${NC}"

        docker builder prune --keep-storage 1GB -f >/dev/null 2>&1 || true
    else
        echo -e "${GREEN}✓ Image already exists${NC}"
        echo -e "  ${CYAN}(use --rebuild to force rebuild, --no-cache for fresh build)${NC}"
    fi
fi

echo -e "${BLUE}[5/5]${NC} Starting container..."

if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
    echo -e "${YELLOW}→ Container already running, restarting...${NC}"
    docker compose -f "$COMPOSE_FILE" restart || {
        echo -e "${RED}✗ Failed to restart container${NC}"
        exit 1
    }
else
    docker compose -f "$COMPOSE_FILE" up -d || {
        echo -e "${RED}✗ Failed to start container${NC}"
        exit 1
    }
fi

echo -e "${YELLOW}→ Waiting for service to be ready...${NC}"
READY=false
for ((i=1; i<=HEALTH_TIMEOUT; i++)); do
    if curl -s --max-time 2 "http://localhost:$PORT/" > /dev/null 2>&1; then
        READY=true
        break
    fi
    printf "\r  %d/%d seconds..." "$i" "$HEALTH_TIMEOUT"
    sleep 1
done
printf "\r                              \r"  # Clear the countdown line

if [[ "$READY" != true ]]; then
    echo -e "${RED}✗ Service did not become ready within ${HEALTH_TIMEOUT}s${NC}"
    echo -e "  Check logs with: ${CYAN}./run-docker.sh --logs${NC}"
    exit 1
fi

echo
echo -e "${GREEN}╔═══════════════════════════╗${NC}"
echo -e "${GREEN}║   Started successfully!   ║${NC}"
echo -e "${GREEN}╚═══════════════════════════╝${NC}"
echo
echo -e "${CYAN}Access the dashboard at:${NC}"
echo -e "  Local:    ${GREEN}http://localhost:$PORT${NC}"

if command -v hostname &> /dev/null; then
    IP=$(hostname -I 2>/dev/null | awk '{print $1}')
    if [ -n "$IP" ]; then
        echo -e "  Network:  ${GREEN}http://$IP:$PORT${NC}"
    fi
fi

echo
echo -e "${CYAN}Useful commands:${NC}"
echo "  View logs:     ./run-docker.sh --logs"
echo "  Stop:          ./run-docker.sh --stop"
echo "  Rebuild:       ./run-docker.sh --rebuild"
echo "  Status:        ./run-docker.sh --status"
echo "  Prune:         ./run-docker.sh --prune"
echo

if [[ "$PRUNE" == true ]]; then
    echo
    do_prune
fi
