from types import SimpleNamespace

from src.cache.playlist import PlaylistCache
from src.playlist.discover import classify_playlist, discover_playlists


def _settings(name="Last.fm Recents (auto)", prefix=None):
    return SimpleNamespace(playlist_name=name, weekly_playlist_prefix=prefix)


def test_classify_main_exact_name():
    cat, autogen, conf = classify_playlist("Last.fm Recents (auto)", "", _settings(), set())
    assert (cat, autogen) == ("main", True)
    assert conf == 1.0


def test_classify_custom_by_name():
    cat, autogen, _ = classify_playlist("Breakcore (auto)", "", _settings(), {"Breakcore (auto)"})
    assert (cat, autogen) == ("custom", True)


def test_classify_weekly_fuzzy_title():
    cat, autogen, _ = classify_playlist("Last.fm Recents week of 2026-06-22", "", _settings(), set())
    assert (cat, autogen) == ("weekly", True)


def test_classify_weekly_bad_date_not_matched():
    cat, autogen, _ = classify_playlist("Last.fm Recents week of nope", "", _settings(), set())
    assert (cat, autogen) == ("unknown", False)


def test_classify_main_by_description_after_rename():
    cat, autogen, conf = classify_playlist("Renamed", "Autogenerated from Last.fm for bob", _settings(), set())
    assert (cat, autogen) == ("main", True)
    assert conf < 1.0


def test_classify_unknown():
    cat, autogen, _ = classify_playlist("My Mixtape", "", _settings(), set())
    assert (cat, autogen) == ("unknown", False)


def test_discover_filters_and_marks_tracked():
    library = [
        {"title": "Last.fm Recents (auto)", "playlistId": "PL1", "count": 50},
        {"title": "Last.fm Recents week of 2026-06-22", "playlistId": "PL2"},
        {"title": "My Mixtape", "playlistId": "PL3"},
    ]
    out = discover_playlists(library, _settings(), set(), tracked_ids={"PL1"})
    ids = {c["id"] for c in out}
    assert ids == {"PL1", "PL2"}
    assert next(c for c in out if c["id"] == "PL1")["tracked"] is True


def test_track_id_writes_id_only(tmp_path):
    pc = PlaylistCache(str(tmp_path / ".pc.json"))
    pc.track_id("Recents", "PLX")
    assert pc.get_id("Recents") == "PLX"
    assert pc.get_video_ids("Recents") == []


def test_track_id_preserves_template(tmp_path):
    pc = PlaylistCache(str(tmp_path / ".pc.json"))
    pc.set_template("Recents", "PLX", ["a", "b"])
    pc.track_id("Recents", "PLY")
    assert pc.get_id("Recents") == "PLY"
    assert pc.get_video_ids("Recents") == ["a", "b"]
