#!/usr/bin/env python3
"""Generate the Project Structure tree in docs/development.md.

Each entry's description is the first line of the matching module or package
docstring (read via ``ast.get_docstring`` - no imports are executed). Directories
that are not Python packages use a literal description defined in ``TREE`` below.

Usage:
    python scripts/gen_structure.py          # rewrite the tree in development.md
    python scripts/gen_structure.py --check   # exit 1 if the tree is out of date

This is run automatically by ./precommit.sh.
"""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "development.md"
BEGIN = "<!-- BEGIN STRUCTURE TREE (generated by scripts/gen_structure.py) -->"
END = "<!-- END STRUCTURE TREE -->"
NAME_WIDTH = 24  # column where the "# description" comment starts

EXCLUDE_DIRS = {"build", "site", "dist", "scripts", "tests", "node_modules", "__pycache__"}

# Non-Python directories have no docstring to read
DIR_DESCRIPTIONS = {
    "config": "User config files (overrides, custom playlists)",
    "cache": "Runtime caches (gitignored)",
    "devops": "Docker setup (Dockerfile, compose, entrypoint)",
    "docs": "This documentation (MkDocs)",
    "web/templates": "Jinja2 HTML templates",
    "web/static": "CSS, JS, icons",
    "web/translations": "i18n catalogs",
}


@dataclass
class Node:
    """One line in the structure tree."""

    name: str
    desc: str
    children: list[Node] = field(default_factory=list)


def is_package(path: Path) -> bool:
    """Whether ``path`` is a Python package (has an ``__init__.py``)."""
    return (path / "__init__.py").is_file()


def keep_dir(path: Path) -> bool:
    """Whether a subdirectory should appear in the tree."""
    name = path.name
    return path.is_dir() and name not in EXCLUDE_DIRS and not name.startswith(".") and not name.endswith(".egg-info")


def py_modules(path: Path) -> list[Path]:
    """Python modules directly in ``path`` (excluding ``__init__.py``), sorted."""
    return sorted((p for p in path.glob("*.py") if p.name != "__init__.py"), key=lambda p: p.name)


def child_dirs(path: Path) -> list[Path]:
    """Subdirectories of ``path`` worth showing - packages first, then alpha."""
    return sorted((p for p in path.iterdir() if keep_dir(p)), key=lambda p: (not is_package(p), p.name))


def docstring_summary(path: Path) -> str:
    """First line of the module/package docstring at ``path`` (``""`` if none)."""
    doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    return doc.strip().splitlines()[0].strip().rstrip(".") if doc else ""


def describe(path: Path) -> str:
    """Description for ``path``: docstring summary, or literal for non-packages."""
    if path.is_file():
        return docstring_summary(path)
    if is_package(path):
        return docstring_summary(path / "__init__.py")
    return DIR_DESCRIPTIONS.get(path.relative_to(ROOT).as_posix(), "")


def leaf(path: Path) -> Node:
    """A childless node for ``path`` (trailing ``/`` for directories)."""
    return Node(path.name + ("/" if path.is_dir() else ""), describe(path))


def build_tree() -> list[Node]:
    """Discover the tree: root modules, then dirs (packages expanded one level)."""
    nodes = [leaf(f) for f in py_modules(ROOT)]
    for directory in child_dirs(ROOT):
        children: list[Node] = []
        if is_package(directory):
            children = [leaf(f) for f in py_modules(directory)] + [leaf(sub) for sub in child_dirs(directory)]
        nodes.append(Node(directory.name + "/", describe(directory), children))
    return nodes


def render(nodes: list[Node], prefix: str = "") -> list[str]:
    """Render ``nodes`` as aligned tree lines with description comments."""
    lines: list[str] = []
    for index, node in enumerate(nodes):
        last = index == len(nodes) - 1
        label = f"{prefix}{'└── ' if last else '├── '}{node.name}"
        if node.desc:
            label = f"{label}{' ' * max(1, NAME_WIDTH - len(label))}# {node.desc}"
        lines.append(label)
        if node.children:
            lines.extend(render(node.children, prefix + ("    " if last else "│   ")))
    return lines


def build_block() -> str:
    """Build the full marker-delimited tree block."""
    body = "\n".join(render(build_tree()))
    return f"{BEGIN}\n```text\n{body}\n```\n{END}"


def apply(text: str) -> str:
    """Return ``text`` with the region between the markers replaced."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"error: markers not found in {DOC.relative_to(ROOT)}.\nAdd a block delimited by:\n  {BEGIN}\n  {END}")
    return text[:start] + build_block() + text[end + len(END) :]


def main() -> int:
    """Rewrite (or, with --check, verify) the structure tree."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the tree is out of date instead of rewriting it",
    )
    args = parser.parse_args()

    current = DOC.read_text(encoding="utf-8")
    updated = apply(current)

    if args.check:
        if current != updated:
            print(
                "docs/development.md structure tree is out of date. Run: python scripts/gen_structure.py",
                file=sys.stderr,
            )
            return 1
        return 0

    if current != updated:
        DOC.write_text(updated, encoding="utf-8")
        print("Updated structure tree in docs/development.md")
    else:
        print("Structure tree already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
