"""Discover and classify autogenerated playlists in the YTM library.

Pure, offline-friendly helpers used by the web dashboard's "Playlists" tab to
find which library playlists were created by this tool (main, weekly, custom
tag), so their IDs can be tracked in the playlist cache and old ones deleted.
"""

from __future__ import annotations

import re
from datetime import date
from typing import TYPE_CHECKING, Any

from .weekly import _derive_weekly_prefix

if TYPE_CHECKING:
    from ..config import Settings

WEEKLY_DESC_MARKER = "Weekly rolling mirror"
MAIN_DESC_MARKER = "Autogenerated from Last.fm"
TAG_DESC_MARKER = "Auto-generated tag playlist"
ARTIST_DESC_MARKER = "Auto-generated artist playlist"

_WEEK_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _is_weekly_title(title: str, base_prefix: str) -> bool:
    """Fuzzy-match a weekly playlist title like '<prefix> week of YYYY-MM-DD'."""
    marker = f"{base_prefix} week of "
    if not title.startswith(marker):
        return False
    tail = title[len(marker) :].strip()
    if not _WEEK_DATE_RE.match(tail):
        return False
    try:
        date.fromisoformat(tail)
    except ValueError:
        return False
    return True


def classify_playlist(
    title: str,
    description: str,
    settings: Settings,
    custom_names: set[str],
) -> tuple[str, bool, float]:
    """Classify a library playlist.

    Returns (category, is_autogenerated, confidence) where category is one of
    ``main``, ``weekly``, ``custom``, ``unknown``. Confidence is 0..1.
    """
    title = (title or "").strip()
    desc = description or ""
    base_prefix = getattr(settings, "weekly_playlist_prefix", None) or _derive_weekly_prefix(settings.playlist_name)

    if title == settings.playlist_name:
        return "main", True, 1.0
    if title in custom_names:
        return "custom", True, 1.0

    if _is_weekly_title(title, base_prefix) or WEEKLY_DESC_MARKER in desc:
        return "weekly", True, 0.9

    if MAIN_DESC_MARKER in desc:
        return "main", True, 0.7
    if TAG_DESC_MARKER in desc or ARTIST_DESC_MARKER in desc:
        return "custom", True, 0.7

    return "unknown", False, 0.0


def discover_playlists(
    library_playlists: list[dict[str, Any]],
    settings: Settings,
    custom_names: set[str],
    tracked_ids: set[str],
    tracked_names: set[str] | None = None,
) -> list[dict[str, Any]]:
    """Classify library playlists into autogenerated candidates.

    Returns a sorted list of dicts with: title, id, category, autogenerated,
    confidence, tracked, track_count.

    A playlist counts as ``tracked`` when either its ID is cached (``tracked_ids``)
    or its title matches a cached entry (``tracked_names``). Title matching is the
    reliable signal because YouTube Music's ``create_playlist`` returns a different
    ID form than ``get_library_playlists``, so a freshly-created playlist's cached
    ID would otherwise never match the library ID.
    """
    tracked_names = tracked_names or set()
    out: list[dict[str, Any]] = []
    for pl in library_playlists:
        title = str(pl.get("title") or "")
        pid = pl.get("playlistId")
        if not isinstance(pid, str) or not pid:
            continue
        desc = str(pl.get("description") or "")
        category, autogen, confidence = classify_playlist(title, desc, settings, custom_names)
        if not autogen:
            continue
        out.append(
            {
                "title": title,
                "id": pid,
                "category": category,
                "autogenerated": autogen,
                "confidence": confidence,
                "tracked": pid in tracked_ids or title in tracked_names,
                "track_count": pl.get("count"),
            }
        )
    out.sort(key=lambda x: (x["category"], x["title"].lower()))
    return out
